name = "gastos-pareja"
main = "src/index.py"
compatibility_date = "2024-12-01"
compatibility_flags = ["python_workers"]

[vars]
SECRET_KEY = "Aliss.102704"
NOMBRE_PERSONA1 = "Ali"
NOMBRE_PERSONA2 = "Zen"

[[d1_databases]]
binding = "DB"
database_name = "gastos_pareja"
database_id = "826a0fb0-731a-4c33-b28c-8a0ea932b4e9"

[assets]
directory = "./static"
