name = "gastos"
main = "src/index.py"
compatibility_date = "2024-12-01"
compatibility_flags = ["python_workers"]

[vars]
SECRET_KEY = "Aliss.102704"
NOMBRE_PERSONA1 = "Ali"
NOMBRE_PERSONA2 = "Zen"

[[d1_databases]]
binding = "DB"
database_name = "gastos_pareja"
database_id = "0468b4ef-5aca-4df2-9fd2-b2f0cb633695"

[assets]
directory = "./static"
